### PR TITLE
projects/metastreet-v2: add queries for tvl and total borrowed value

### PR DESCRIPTION
**Pull request by wegory**
Once merged to main, will create a PR into DefiLlama's repo: https://docs.llama.fi/list-your-project/submit-a-project

MetaStreet V1 reference: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/metastreet/index.js

To test: `npm install && node test.js projects/metastreet-v2/index.js`

---
##### Name (to be shown on DefiLlama):
MetaStreet V2

##### Twitter Link:
https://twitter.com/metastreetxyz

##### List of audit links if any:
https://docs.metastreet.xyz/v2/audits

##### Website Link:
https://www.metastreet.xyz/

##### Logo (High resolution, will be shown with rounded borders):
metastreet logo

##### Current TVL:
~768k USD

##### Treasury Addresses (if the protocol has treasury)
N.A.

##### Chain:
Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
N.A.

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
N.A.

##### Short Description (to be shown on DefiLlama):
The MetaStreet v2 Pool is a permissionless lending pool for NFT collateral with automatic tranching. Pool is responsible for organizing lending capital with different risk and rate profiles from depositors into fixed-duration loans for borrowers.

##### Token address and ticker if any:
N.A.

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N.A.

##### forkedFrom (Does your project originate from another project):
N.A.

##### methodology (what is being counted as tvl, how is tvl being calculated):
TVL is calculated by summing the total value of all liquidity nodes across all pools. The TVL includes tokens available, tokens loaned out, and interest earned. Total borrowed is calculated by subtracting the tokens available from the total value of all liquidity nodes across all pools.

##### Github org/user (Optional, if your code is open source, we can track activity):
To be added in future

### CODE REVIEW

**Comment by vsergeev** [comment]
Looks good to me, I think we may just want to reword the description a bit

TVL is calculated by summing the total value of all liquidity nodes across all pools. The TVL includes tokens available, tokens loaned out, and interest earned. Total borrowed is calculated by subtracting the tokens available from the total value of the all liquidity nodes across all pool.

Let me know if you think that can be better...

**Comment by wegory** [comment]
> Looks good to me, I think we may just want to reword the description a bit
> 
> TVL is calculated by summing the total value of all liquidity nodes across all pools. The TVL includes tokens available, tokens loaned out, and interest earned. Total borrowed is calculated by subtracting the tokens available from the total value of the all liquidity nodes across all pool.
> 
> Let me know if you think that can be better...

Nice, this looks better

**Comment by vsergeev** [comment]
Just one typo I had in there: "of the all" should be "of all"

**Comment by wegory** [comment]
> Just one typo I had in there: "of the all" should be "of all"

Fixed that and changed "pool" to "pools" at the end of the paragraph.

**Review by vsergeev — APPROVED** [review]
LGTM, let's PR to their repo.

**Pull request merged**
